<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/3d/3DGodotRobot.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  let action = 'Run-loop'
  const gltf = useGltf('/3d/3DGodotRobot.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions[action]?.play()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="RobotArmature" scale={0.58}>
        <T is={gltf.nodes.spine} />
        <T.SkinnedMesh
          name="Bottom"
          geometry={gltf.nodes.Bottom.geometry}
          material={gltf.materials.Material}
          skeleton={gltf.nodes.Bottom.skeleton}
        />
        <T.SkinnedMesh
          name="Chest"
          geometry={gltf.nodes.Chest.geometry}
          material={gltf.materials.Material}
          skeleton={gltf.nodes.Chest.skeleton}
        />
        <T.Group name="Face">
          <T.SkinnedMesh
            name="Cube003"
            geometry={gltf.nodes.Cube003.geometry}
            material={gltf.materials.Material}
            skeleton={gltf.nodes.Cube003.skeleton}
          />
          <T.SkinnedMesh
            name="Cube003_1"
            geometry={gltf.nodes.Cube003_1.geometry}
            material={gltf.materials['Material.002']}
            skeleton={gltf.nodes.Cube003_1.skeleton}
          />
        </T.Group>
        <T.SkinnedMesh
          name="Llimbs_and_head"
          geometry={gltf.nodes.Llimbs_and_head.geometry}
          material={gltf.materials.Material}
          skeleton={gltf.nodes.Llimbs_and_head.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
